# Prometheus configuration for Federated Medical RAG System
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'federated-medical-rag'
    environment: 'production'

# Scrape configurations
scrape_configs:
  # Flower Server metrics
  - job_name: 'flower-server'
    static_configs:
      - targets: ['flower-server:8080']
    metrics_path: '/metrics'
    
  # API Server metrics
  - job_name: 'api-server'
    static_configs:
      - targets: ['api-server:8000']
    metrics_path: '/metrics'
    
  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alert rule files
rule_files:
  - 'alerts.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

